[theme]
primaryColor="#8C00FF"
backgroundColor="#20004F"
secondaryBackgroundColor="#5700A3"
textColor="white"
font="sans serif"
base="dark"
[server]
maxUploadSize = 15
enableXsrfProtection = false
enableCORS = true