[theme]
primaryColor="#8C00FF"
backgroundColor="#20004F"
secondaryBackgroundColor="#5700A3"
linkColor="#0000FF"
visitedLinkColor="#0000FF"
hoverLinkColor="#0000FF"
activeLinkColor="#0000FF"
textColor="white"
font="sans serif"
base="dark"
[server]
maxUploadSize = 15