[theme]
primaryColor="darkgrey"
backgroundColor="#f2f2f2"
secondaryBackgroundColor="white"
textColor="black"
font="sans serif"
base="light"
[server]
maxUploadSize = 150
enableXsrfProtection = false
enableCORS = false